// Generated by CoffeeScript 1.9.2
var app, port, server;

app = require('./app');

port = process.env.PORT || 3000;

server = app.listen(port, function() {
  var addr;
  addr = server.address();
  return console.log("Listening at http://%s:%d", addr.address, addr.port);
});
