// Generated by CoffeeScript 1.9.2
var BloomFilterTokenSet, TextTokenSet;

BloomFilterTokenSet = require('./BloomFilterTokenSet');

TextTokenSet = require('./TextTokenSet');

module.exports = {
  geonames: new TextTokenSet.Factory(__dirname + '/../data/geonames.txt.gz', 5)
};
