// Generated by CoffeeScript 1.9.2
var TokenSet;

module.exports = TokenSet = (function() {
  function TokenSet(maxNgramSize) {
    this.maxNgramSize = maxNgramSize;
  }

  TokenSet.prototype.test = function(token) {
    throw new Error('not implemented');
  };

  TokenSet.prototype.findTokensFromUnigrams = function(unigrams) {
    var byte, i, len, pos, ret, startPositions, testNgrams, unigramsBuffer;
    unigramsBuffer = new Buffer(unigrams.join(' ').toLowerCase(), 'utf-8');
    startPositions = new Array(0);
    ret = [];
    testNgrams = (function(_this) {
      return function(endPosition) {
        var i, len, s, startPosition;
        for (i = 0, len = startPositions.length; i < len; i++) {
          startPosition = startPositions[i];
          if (_this.test(unigramsBuffer, startPosition, endPosition)) {
            s = unigramsBuffer.toString('utf-8', startPosition, endPosition);
            ret.push(s);
          }
        }
        return null;
      };
    })(this);
    for (pos = i = 0, len = unigramsBuffer.length; i < len; pos = ++i) {
      byte = unigramsBuffer[pos];
      if (byte === 0x20) {
        testNgrams(pos);
        if (startPositions.length === this.maxNgramSize) {
          startPositions.shift();
        }
        startPositions.push(pos + 1);
      }
    }
    while (startPositions.length > 1) {
      testNgrams(unigramsBuffer.length);
      startPositions.shift();
    }
    return ret;
  };

  return TokenSet;

})();
